CT-546 api docs with json - part 2
keboola/storage-api-php-client pull request #1018
Opened 2023-03-09 10:22 UTC by martinjunger

Jira: CT-546
KBC: XXX

---
Updated sections:
- workspaces
- events
- metadata
- ...

---
Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-03-13 09:27 UTC, jirkasemmler requested changes

2023-03-13 09:27 UTC, jirkasemmler commented on apiary.apib
> +    + rowsSortOrder[] (optional, string) - Array of row ids in desired order, you have to specify all row ids
pripadne array[string]

2023-03-14 09:48 UTC, martinjunger commented on apiary.apib
> +    + rowsSortOrder[] (optional, string) - Array of row ids in desired order, you have to specify all row ids
jo, muze byt, upraveno. Nechtel jsem do toho zanaset velkou opravu vseho :-)

2023-03-14 09:50 UTC, martinjunger commented on apiary.apib
> +    + targetConfigId (optional, string) - Copy the row to another existing configuration. If not provided, the row will be copied to the original configuration.
ok, muze byt, upraveno.

2023-03-14 09:59 UTC, jirkasemmler approved these changes

2023-03-14 10:00 UTC, merged