CT-971 return definition
keboola/storage-api-php-client pull request #1047
Opened 2023-04-17 13:23 UTC by zajca

Jira: CT-971
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-04-17 14:48 UTC, jirkasemmler requested changes
dopsal bych par poznamek do te dokumentace. jak moc to frci zkusim zitra. exasol asi ne, snflk asi jo.

2023-04-18 11:02 UTC, jirkasemmler requested changes
exasol jsem fixnul, frci. Ale prosim dopln to do te dokumentace.

2023-04-18 18:16 UTC, zajca commented on apiary.apib
> +                "definition": {
[Přidal sem](https://github.com/keboola/storage-api-php-client/pull/1047/commits/1dfc0f94411303310e90cb7354d7fe17f3e15f84), ale nevím co myslíš tím pro konfigurace.

2023-04-18 19:07 UTC, jirkasemmler commented on apiary.apib
> +                "definition": {
Myslím tím objekt configuration, který je samozřejmě pro TwC ale mohli bychom to tam doplnit, že ten objekt se vrací pokud tabulka má definovanou konfiguraci. Ale netrvam na tom

2023-04-19 06:54 UTC, jirkasemmler approved these changes

2023-04-19 07:04 UTC, merged