CT-1009add testCreateTableDefaults for SNFLK
keboola/storage-api-php-client pull request #1059
Opened 2023-05-23 12:12 UTC by zajca

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-05-26 12:25 UTC, tomasfejfar requested changes
Buď něco nechápu, nebo to na pár místech projde i když by nemělo 🤔

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                ],
Ještě by tu měl být case na default decimal value, ne?

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                ],
Tj. 1.35 třeba

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                ],
tady by měl být taky 1.33 třeba

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                ],
(a u všech float-like)

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
Tohle by mělo spadnout, ne? To prostě není správný string - je to jako kdyby uživatel chtěl zadat nějaký jiný sloupec jako default

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test',
jaktože to nespadne, když default je CHAR(1) ? 🤔

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
mělo by spadnout

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
oboje i u těch ostatních char-like

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
mělo by spadnout

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
a všude dál

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
```suggestion
                    'value' => 'test', // SNFLK will take as false when escaped
```

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
tvl fakt! 
![image](https://github.com/keboola/storage-api-php-client/assets/642928/360eb3cd-afee-4f9b-b8f0-c50df97eee7f)

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
Akorát to pak spadne ve SNFLK na insertu 
![image](https://github.com/keboola/storage-api-php-client/assets/642928/c085f44d-154a-4a19-9e7c-586228e5e1bf)

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
```
CREATE OR REPLACE TABLE mytable (id boolean DEFAULT 'test', num number);
SHOW SCHEMAS;
USE SCHEMA WORKSPACE_947738;
DESC TABLE mytable;
INSERT INTO mytable (num) VALUES (1);

```

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
Tj. bude nám to sypat app errory při importu

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
:(

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => '\'00:00:00\'',
Tohle by mělo projít, ne? 

Aha, tak ne. Musí se to udělat takhle:

    CREATE OR REPLACE TABLE mytable (id boolean DEFAULT 'test', cas TIME DEFAULT '00:00:00'::time, num number);

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => '\'2021-01-01 00:00:00\'',
dtto jako time (a date)

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
```
CREATE OR REPLACE TABLE mytable (id boolean DEFAULT "test", cas TIME DEFAULT '00:00:00'::time, num number);
[42000][904] SQL compilation error: error line 1 at position 52 invalid identifier '"test"'
```

2023-05-26 12:25 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
s varchar column to dělá stejně

2023-05-26 12:28 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'expectFail' => [],
CREATE OR REPLACE TABLE mytable (id boolean DEFAULT '"test"', cas TIME DEFAULT '00:00:00'::time, num number);

2023-05-26 12:32 UTC, tomasfejfar commented on tests/Backend/Snowflake/TableDefinitionOperationsTest.php
> +                    'value' => 'test', // SNFLK will take is false when escaped
vyřešíme v separatní issue pro import

2023-05-26 13:51 UTC, zajca commented
Přidal sem floaty a opravil bool a date

2023-05-29 07:57 UTC, tomasfejfar approved these changes

2023-05-29 08:25 UTC, merged