Jirka sox 13 create mr
keboola/storage-api-php-client pull request #1080
Opened 2023-06-15 23:58 UTC by jirkasemmler

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-06-16 06:22 UTC, jirkasemmler commented on apiary.apib
> +                },
nevim co se tady zmenilo

2023-06-16 09:33 UTC, jirkasemmler commented
hmm, doslo mi, ze vubec necheckuju nalezitost tech branchi k projektu... dodelam

2023-06-16 10:47 UTC, zajca approved these changes
Testy vypadajů v cajku

2023-06-16 10:47 UTC, zajca commented on apiary.apib
> +                },
nějaké whitespace

2023-06-16 10:52 UTC, zajca requested changes
Ještě bys měl udělat check, že má projekt tu feature.

2023-06-19 07:15 UTC, zajca commented
BTW: bude to fungovat na normální projektu teď, ale na SOX projektu ne. Protože create branch děláš master tokenem což je normálně admin :) Ale když přepneš na SOX tak to bude productionManager a ten nemože založit branch :) 
Tak nevím na jakém projektu to plánuješ pustit ty testy. Protože předpokládám na SOX tak bys to měl testovat tak, že developer a reviewer može pracovat s tím MR, ale productionManager ne :)

2023-06-19 08:55 UTC, jirkasemmler commented
> BTW: bude to fungovat na normální projektu teď, ale na SOX projektu ne. Protože create branch děláš master tokenem což je normálně admin :) Ale když přepneš na SOX tak to bude productionManager a ten nemože založit branch :) Tak nevím na jakém projektu to plánuješ pustit ty testy. Protože předpokládám na SOX tak bys to měl testovat tak, že developer a reviewer može pracovat s tím MR, ale productionManager ne :)

@zajca Moje uvaha je takova, ze ted bych to mergnul a nechal jet na beznem adminovi a az bude vyresena SOX suita, tak mam v planu vsechny ty MR testy strcit pod ni a resit tam i ta prava. Kazdopadne z meho chapani roli by cist a vytvorit MR mohl kdokoliv (sox role) ne?

2023-06-19 08:58 UTC, zajca approved these changes

2023-06-19 11:57 UTC, merged