SOX-21 table pull
keboola/storage-api-php-client pull request #1115
Opened 2023-07-07 13:44 UTC by zajca

Jira: SOX-21
KBC: https://github.com/keboola/connection/pull/4464

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-07-10 11:36 UTC, romanbracinik reviewed
Mozno by bolo dobre otestovat aj ine akcie ako len update metadat, napr pridanie alebo odobranie stlpcov. Mozno dalsi test na typovanu tabulku a tak. Inac testy presli

2023-07-11 12:03 UTC, zajca commented
> Mozno by bolo dobre otestovat aj ine akcie ako len update metadat, napr pridanie alebo odobranie stlpcov. Mozno dalsi test na typovanu tabulku a tak. Inac testy presli

Přidal sem asserty na eventy. přidal sem přidání odebrání sloupce a test na tabulku s typama.

2023-07-11 12:24 UTC, romanbracinik requested changes
Jedna mala drobnost k eventam a bude to vsetko, PR connection je cajk

2023-07-11 12:54 UTC, zajca commented on tests/Backend/SOX/PullTableTest.php
> +        $event = $this->createAndWaitForEvent(
Na to si snad nezvyknu :D

2023-07-11 12:56 UTC, romanbracinik approved these changes
cool 👍

2023-07-11 14:14 UTC, merged