test cross crud buckets
keboola/storage-api-php-client pull request #1153
Opened 2023-08-01 13:02 UTC by romanbracinik

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-08-04 13:07 UTC, jirkasemmler requested changes
lgtm, jen nerozumim tomu cleanupu. A ten error - zkus to brances dat public. nevim jak se tam chova ten provider, jestli nahodou nevystoupi z classy

2023-08-08 10:49 UTC, romanbracinik commented
@jirkasemmler funguje to tak, ze
- provider sa zavola pred setUp
- tim ze v provideru potrebujem branch klienta tak tam tu branch musim vytvorit
- ale ked ten test spustim 2x tak v provideru kde vytvaram novu branch tak tam pre ten dany test existuje, takze tam musi byt aj mazanie branche aby to preslo
- potom sa zavola setUp kde je tiez mazanie
- ale tim ze tu branch som vytvoril v provideru tak nema prefix toho testu a tak v tom setupe sa to uz nezmaze a test prejde.

2023-08-08 11:17 UTC, romanbracinik commented
Tak som to trochu upravil

2023-08-08 19:56 UTC, jirkasemmler approved these changes

2023-08-09 05:33 UTC, merged