SOX-352 refresh
keboola/storage-api-php-client pull request #1160
Opened 2023-08-08 10:06 UTC by tomasfejfar

Jira: SOX-352
KBC: XXX

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
  **BC break, ale jen v experimentální části**
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-08-10 11:22 UTC, tomasfejfar commented
Přidal jsem testy na can create jobs + jsem udělal ten cleanup, ať se nám nehromadí tokeny.

2023-08-11 08:30 UTC, zajca requested changes
řejk, mám jedu věcičku

2023-08-11 08:30 UTC, zajca commented on tests/Backend/SOX/SOXTokensTest.php
> +        }
řekl bych že by tu měl byt ještě revjůvr

2023-08-11 09:10 UTC, tomasfejfar commented on tests/Backend/SOX/SOXTokensTest.php
> +        }
Done.

2023-08-11 09:11 UTC, zajca approved these changes

2023-08-14 08:50 UTC, merged