Ct 1138 dont create new brach every run
keboola/storage-api-php-client pull request #1195
Opened 2023-10-04 08:52 UTC by romanbracinik

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-10-10 05:56 UTC, romanbracinik commented on tests/ClientProvider/TestSetupHelper.php
> +                $branch = $devBranches->createBranch($branchName);
vytvaram novu branch len ked neexistuje pre dany test, vsade kde sa to pouziva sa nejakou formou premazavaju buckty/metadata a pod. takze test prechadza a myslim si e to pomaha na err You don't have access to resource.

2023-10-10 05:58 UTC, romanbracinik commented on tests/Backend/CommonPart1/BucketsTest.php
> +        $this->assertGreaterThan(2, $bucketEvents);
tim ze sa pouziva stale jedna branch a nevytvara nova tak je to ako v maine a tych eventov tam moze byt viac

2023-10-10 08:30 UTC, jirkasemmler requested changes

2023-10-10 08:30 UTC, jirkasemmler commented on tests/Backend/CommonPart1/BucketsTest.php
> +        $bucketName = sha1($this->generateDescriptionForTestObject()).'-testBucketDetail';
to co delas by melo udelat i getTestBucketId() ne? Jen teda nechapu v cem toto ma pomoci

2023-10-10 08:30 UTC, jirkasemmler commented on tests/ClientProvider/TestSetupHelper.php
> +        foreach ($branchesCreatedByThisTestMethod as $branch) {
`return reset(branchesCreatedByThisTestMethod) ?: null;`

2023-10-10 13:02 UTC, romanbracinik commented on tests/Backend/CommonPart1/BucketsTest.php
> +        $bucketName = sha1($this->generateDescriptionForTestObject()).'-testBucketDetail';
Hmm no jasne, neviem asi som to v tom ako som to rozne skusal upravil stim, ze to ma nejaky vyznam a pak som zil v tej domienke ze to tak ma byt:) Dik zmazal som to.

2023-10-10 13:03 UTC, romanbracinik commented
Dik upravil som to a davam na review @jirkasemmler

2023-10-12 13:33 UTC, jirkasemmler commented on tests/ClientProvider/TestSetupHelper.php
> +        $branch = reset($branchesCreatedByThisTestMethod) ?: null;
```suggestion
        $branch = reset($branchesCreatedByThisTestMethod);
```

2023-10-12 13:34 UTC, jirkasemmler commented on tests/ClientProvider/TestSetupHelper.php
> +        if ($branch === null) {
```suggestion
        if ($branch === false) {
```

2023-10-12 13:34 UTC, jirkasemmler commented on tests/ClientProvider/TestSetupHelper.php
> +        $branch = reset($branchesCreatedByThisTestMethod) ?: null;
ten ternarni operator jsem tam daval jen protoze `reset` vraci `false` pokud je pole prazdne

2023-10-12 13:35 UTC, jirkasemmler requested changes
jen malickost.

2023-10-12 13:43 UTC, jirkasemmler approved these changes

2023-10-12 15:24 UTC, merged