test export
keboola/storage-api-php-client pull request #1297
Opened 2024-03-19 15:06 UTC by romanbracinik

Jira: CT-1325
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-03-22 00:22 UTC, jirkasemmler requested changes
cajk, jen prosim dopln poznamku o tom, ze z EB nejde delat snapshoty sem https://keboola.docs.apiary.io/#reference/table-snapshotting/create-or-list-snapshots a sem https://help.keboola.com/storage/byodb/external-buckets/#limitations

2024-03-22 06:58 UTC, romanbracinik commented
> cajk, jen prosim dopln poznamku o tom, ze z EB nejde delat snapshoty sem https://keboola.docs.apiary.io/#reference/table-snapshotting/create-or-list-snapshots a sem https://help.keboola.com/storage/byodb/external-buckets/#limitations

[c0119ea](https://github.com/keboola/storage-api-php-client/pull/1297/commits/c0119ea4153b9b70935b3094e035b95a9cd2e46b) 
<img width="570" alt="Screenshot 2024-03-22 at 7 56 33" src="https://github.com/keboola/storage-api-php-client/assets/6448364/5001a60b-fc16-4779-99e8-9890604eb20b">

2024-03-25 06:55 UTC, jirkasemmler approved these changes

2024-03-25 12:17 UTC, romanbracinik commented
rebase

2024-03-25 12:20 UTC, merged