CT-1340 table import ordered columns
keboola/storage-api-php-client pull request #1317
Opened 2024-04-15 08:45 UTC by martinjandl

Jira: [CT-1340](https://keboola.atlassian.net/browse/CT-1340)
KBC: [4954](https://github.com/keboola/connection/pull/4954)

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-04-15 14:04 UTC, zajca requested changes
Ten test by to chtělo ještě poštelovat. Měl by failnůt na aktuálním masteru.
Tím že `languages-without-headers.csv` je id,name tak není rozdíl v tom jestli je to z metadata nebo z columns. 
Prohodil bych ty sloupce a otestoval přes preview, že je to naimportované ve správném sloupci.

2024-04-16 07:14 UTC, zajca commented
Jo padá to sorry. Akorát teda nevím jestli to, že full load změní pořádí sloupců není nechtěný side-efekt :thinking:

2024-04-16 07:31 UTC, martinjandl commented
Mam pocit, ze jsme dosli k tomu, ze z pohledu dalsiho pouziti tabulky na poradi sloupcu nezalezi... ale nedokazu dohlednout:(

2024-04-16 07:47 UTC, zajca commented
> Mam pocit, ze jsme dosli k tomu, ze z pohledu dalsiho pouziti tabulky na poradi sloupcu nezalezi... ale nedokazu dohlednout:(

Sem si to pozkůšal, že je to konzistentní a sloupce to přeháže vždycky (BQ aj SNFLK) takže ať tam je/není PK, nebo ať je to full/incremental load tak to vždycky přeháže sloupce podle toho co tam přišlo v columns.
Co myslíš @tomasfejfar? Teoreticky by to ničemu nemělo vadit ve storage. Prakticky by to možná mohlo udělat nějaků neplechu v transformaci když používáš RO storage, ale většinů máš výčet sloupců takže by to problém byt nemusel.

Bylo by fajn pokrýt hlavně ten incremental v testu a otestovat data preview aby tam bylo vidět že je to přeházané.
Místo `languages-headers.csv` bych udělal create nad `languages.csv` a pak udělal incremental.
Mohlo by to mět provider.
```
incremental: bool,
expectedData: array
```
Tady je vidět jak použit preview, enom bych mu nepředával obsah souboru.
https://github.com/keboola/storage-api-php-client/blob/52b53cf0caf3fa35be27aeb10ec66e83a6dc8ca3/tests/Backend/CommonPart1/ImportExportCommonTest.php#L367-L369

2024-04-16 07:55 UTC, tomasfejfar commented
No já si hned umím představit scénář kdy přeházení sloupců vadí :) 

```
$sql = 'SELECT * FROM "in.c-mujbucket"."tabulka"';
$exportedCsv = $this->exportToCsv($sql);  // export bez headeru
$row = fgetcsv($exportedCsv);
$id = $row[0]
```

Něco takovýho určitě může mít někdo v python transformaci.

2024-04-16 08:00 UTC, zajca commented
> No já si hned umím představit scénář kdy přeházení sloupců vadí :)
> 
> ```
> $sql = 'SELECT * FROM "in.c-mujbucket"."tabulka"';
> $exportedCsv = $this->exportToCsv($sql);  // export bez headeru
> $row = fgetcsv($exportedCsv);
> $id = $row[0]
> ```
> 
> Něco takovýho určitě může mít někdo v python transformaci.

To bude slušný ořech ty sloupce nepřehazovat :)

2024-04-16 08:04 UTC, zajca commented
Vlastně nevím proč sa ty sloupce přehážů, při tom full loadu sa nedělá drop té tabulky. 
- Udělá sa stage s pořádím cos poslal
- Truncate cílové
- insert into ze stage do cílové

2024-04-16 08:08 UTC, zajca commented
Aha už vím proč sa to změní :) ordinal ve storage neodpovídá ordinal v databázi :) 
Na konci sa dělá:
`$state->setImportedColumns($stagingTableDefinition->getColumnsNames());`
takže to vezne columns ze stage a ne z final.

2024-04-16 08:16 UTC, zajca commented
Takže bych řekl že sa bude muset každá třída co implementuje `Keboola\Db\ImportExport\Backend\ToFinalTableImporterInterface` aby to brala s destination, akorát je tam navíc _timestamp. Takže možná vzít pořadí z destination, ale výčet ze stage.

2024-04-18 11:33 UTC, martinjandl commented
Upravil jsem testy, aby tam byl full i incremental s prehozenymi sloupci.

2024-04-18 13:02 UTC, zajca commented on tests/Backend/CommonPart1/ImportExportCommonTest.php
> +            ],
asi v pohodě, ale nevím moc co ten test dělá takového navíc

2024-04-18 16:39 UTC, martinjandl commented on tests/Backend/CommonPart1/ImportExportCommonTest.php
> +            ],
Zamýšlel jsem více inkrementálních importů po sobě do prázdné tabulky..

2024-04-18 17:05 UTC, martinjandl commented on tests/Backend/CommonPart1/ImportExportCommonTest.php
> +            'expectedData' => '"0","- unchecked -"' . PHP_EOL . '"1","english"' . PHP_EOL . '"11","finnish"' . PHP_EOL . '"24","french"' . PHP_EOL . '"26","czech"' . PHP_EOL .  '"id","name"' . PHP_EO
jo no, je to citelnejsi

2024-04-18 17:08 UTC, martinjandl commented
Koukas spravne, chybu, pridam. Rikal jsem si, ze ten table preview to vraci v poradi v jakem ma tabulka sloupce..

2024-04-19 08:31 UTC, martinjandl commented
Přidal jsem test, který importuje data s novým sloupcem poslaným v columns

2024-04-22 12:20 UTC, zajca approved these changes
:+1:

2024-04-22 12:32 UTC, merged