Test import csv withoutHeaders=false and specified columns
keboola/storage-api-php-client pull request #1321
Opened 2024-04-24 13:32 UTC by martinjandl

Jira: [CT-1340](https://keboola.atlassian.net/browse/CT-1340)
KBC: XXX

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-04-25 14:11 UTC, martinjandl commented
@tomasfejfar navrh reseni https://github.com/keboola/connection/pull/5000

2024-04-25 15:58 UTC, odinuv commented
Snad jo, ale nemám teď už mentální kapacitu se nad tím zamyslet. 

Co se týče BC - tak teď je to tak, že columns automaticky nastavít withoutHeaders=true. Co když bych explicitně poslal columns a withoutHeaders=false - v současné verzi to neudělá nic a v nové by to respektovalo withoutHeaders?

2024-04-25 16:23 UTC, martinjandl commented
Nová verze se kvůli BC neobejde bez nového parametru, který prostě withoutHeaders přebije. Podobu nové verze řešíme zde https://github.com/keboola/connection/pull/5000

Tak až najdeš mentální kapacitu, mrkni prosím na ten test :)

2024-04-30 06:39 UTC, odinuv reviewed
jo, ten test popisuje usecase co potřebujem. 
(k tomu potřebujem ještě to, aby to samý šlo provést s datovým souborem bez hlavičky)

2024-04-30 06:39 UTC, odinuv commented on tests/Backend/CommonPart1/ImportExportCommonTest.php
> +            'headersFile' => __DIR__ . '/../../_data/languages-headers.csv',
Note to self: tohle vytvoří tabulku se sloupci id, name
https://github.com/keboola/storage-api-php-client/blob/a7e249b5549feca3c0652cfa5ae1923ac5d4ee3c/tests/_data/languages-headers.csv#L1

2024-05-09 12:33 UTC, tomasfejfar requested changes
https://keboolaglobal.slack.com/archives/C056FD1SEAG/p1715256241522029?thread_ts=1715254430.549909&cid=C056FD1SEAG

2024-05-10 10:15 UTC, tomasfejfar approved these changes
Teď už LGTM

2024-05-10 11:18 UTC, martinjandl commented on tests/Backend/CommonPart1/ImportExportCommonTest.php
> +            'ignoredLinesCount' => null,
Ano, původně se s columns setovalo withoutHeaders vždy na true.
Zároveň se columns ignorovaly, když bylo withoutHeaders=true

`
       if ($importOptions->getWithoutHeaders()) {
            $importOptions->setColumns($table->getMetadataColumnNames());
        } elseif ($importOptions->getColumns() !== []) {
            $importOptions->setWithoutHeaders(true);
            $importOptions->setColumns($this->normalizeColumnNames($importOptions->getColumns()));
        } else {
        ...
`

2024-05-13 09:35 UTC, merged