CT-1439 refresh tables information test
keboola/storage-api-php-client pull request #1345
Opened 2024-05-31 12:19 UTC by vojtabiberle

Jira: [CT-1439](https://keboola.atlassian.net/browse/CT-1439)
KBC: https://github.com/keboola/connection/pull/5104

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-06-03 14:29 UTC, jirkasemmler requested changes
ten ws mi prijde uplne zbytency

2024-06-04 10:21 UTC, jirkasemmler commented on tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
> +        $wsBackend = WorkspaceBackendFactory::createWorkspaceBackend($workspace);
[tady](https://keboolaglobal.slack.com/archives/C0553EM2RGX/p1717487610163069?thread_ts=1717148722.586599&cid=C0553EM2RGX) jsme se dohodli, ze ten WS je ok. Jen tady ten radek je zbytecny ne? ta promenna `wsBackend` se nikde nepouziva

2024-06-04 11:11 UTC, jirkasemmler commented on tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
> +        $wsBackend = WorkspaceBackendFactory::createWorkspaceBackend($workspace);
```suggestion
```

2024-06-04 11:11 UTC, jirkasemmler requested changes
jen zrusit tu promennou

2024-06-04 11:52 UTC, vojtabiberle commented on tests/Backend/ExternalBuckets/SnowflakeBucketsRefreshTablesInformationTest.php
> +        $wsBackend = WorkspaceBackendFactory::createWorkspaceBackend($workspace);
pravda, odstraněno

2024-06-04 12:03 UTC, merged

2024-06-05 19:46 UTC, ondrajodas commented
v klientovi by nemělo být omezení na branch... když to teď zavolám přes BranchAwareClient tak to bude volat url `branch/ID/branch/ID/buckets...`