FIX tokens tests respect token visibility
keboola/storage-api-php-client pull request #1365
Opened 2024-07-03 14:02 UTC by vojtabiberle

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-07-03 18:36 UTC, zajca requested changes
abych pravdu řekl tak ten assertIfTokenIsVisible mě přide dost nepřehledný proti zavolání toho ifu přímo.

2024-07-03 18:37 UTC, zajca requested changes
moc sa mě to nelíbý vyhodil bych ten assertIfTokenIsVisible přijde mě zbytečný a zavolat `if ($this->isTokenStringVisible($token)) {` mě přijde o dost přehlednější.

2024-07-03 20:13 UTC, vojtabiberle commented
hele jako klidně `if`, původně jsem to tak dokonce měl, ale přišlo mi to takhle hezčí, ale ve výsledku je mi tohle fakt fuk

jestli se to tobě bude číst lépe s `if`em, tak bude `if` :-)

2024-07-04 06:08 UTC, zajca approved these changes
je to takto prostě lepší :D

2024-07-04 06:09 UTC, merged