Update apiary.apib
keboola/storage-api-php-client pull request #1414
Opened 2024-10-29 08:57 UTC by tomasfejfar

https://github.com/keboola/ai-service/pull/131/files/4b0b1189ca6d08151516d4357372591212fd632c#r1820368987

Jira: CT-XXX
KBC: XXX

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] New client method(s) support branches, or they are listed in BranchAwareClient 
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2024-10-29 09:32 UTC, jirkasemmler requested changes
jen si to chci vyjasnit, jinak ok

2024-10-29 09:32 UTC, jirkasemmler commented on apiary.apib
> +Deletes a configuration. When a configuration is deleted, it is only marked as deleted and remains still available in the system.
```suggestion
Deletes a configuration in specified branch. When a configuration is deleted, it is only marked as deleted and remains still available in the system.
```

2024-10-29 09:32 UTC, jirkasemmler commented on apiary.apib
> +Deletes a configuration. When a configuration is deleted, it is only marked as deleted and remains still available in the system.
jakoze nevim proc ti ten `Deletes a development branch configuration` vadil . zni sice divne, ale imho ma pravdu a melo by se to zminit. Nebo ne?

2025-04-23 12:04 UTC, tomasfejfar commented on apiary.apib
> +Deletes a configuration. When a configuration is deleted, it is only marked as deleted and remains still available in the system.
Primárně vadilo, že říká jen "development branch" a ne "or production". Tvoje formulace je OK

2025-04-28 10:56 UTC, zajca approved these changes

2025-05-12 11:32 UTC, merged