KBC-654 add DataPreviewLimitsTest::testSimplePreview to check preview data
keboola/storage-api-php-client pull request #471
Opened 2020-08-25 07:25 UTC by zajca

2020-08-26 15:21 UTC, ErikZigo submitted a review, later dismissed
👍

2020-08-26 16:21 UTC, ErikZigo requested changes
Test musí být víc striktní a validovat pořadí sloupc a jejich hodnot. Viz můj comment v PR kbc

2020-08-27 08:02 UTC, zajca commented
Test sem upravil kontroluje pořadí sloupců

2020-08-28 12:43 UTC, ErikZigo approved these changes
Super tenhle test už vypadá stabilně

2020-09-01 08:39 UTC, merged