KBC-866 Add "creatorToken" to branches
keboola/storage-api-php-client pull request #485
Opened 2020-09-22 11:08 UTC by tomasfejfar

KBC-866

Code: https://github.com/keboola/connection/pull/2758

2020-09-24 12:52 UTC, zajca requested changes
Chybý dokumentace k API. Proč to není creatorAccessToken stejně jak v DB?

2020-09-24 13:04 UTC, tomasfejfar commented
Tvl, no jasně, že chybí docs... :/ 

creator token je standardní věc napříč celým API (veřejná) tak proto jsem to nechal. Ale v DB je to normálně jako "idAccessToken a "accessTokenName" (třeba u jobs) a na to jsem neměl nervy to pojmenovat takhle nekonzistentně :) 
![image](https://user-images.githubusercontent.com/642928/94148168-905f9280-fe76-11ea-9767-aa91b9a0f4d7.png)

2020-09-24 13:21 UTC, tomasfejfar commented
Rovnou jsem i fixnul chybějící čárky v JSONu a odsazení,

2020-09-24 13:34 UTC, zajca approved these changes

2020-10-02 06:55 UTC, zajca approved these changes
Ty jo vůbec sem si nevšiml, že je to znova na review, sorry :/
Ten main PR mám taky udělat review?

2020-10-02 09:55 UTC, tomasfejfar commented
Jo, taky. Sorry, tam jsem udělal chybu, že jsem jen dismissnul to poslední review a nedošlo mi, že musím ještě re-requestnout nový...

2020-10-02 09:55 UTC, tomasfejfar commented
Ještě to rebasnu

2020-10-02 09:57 UTC, tomasfejfar commented
Oboje rebasnuto.

2020-10-05 10:21 UTC, merged