KBC-1058 ABS retry
keboola/storage-api-php-client pull request #515
Opened 2020-11-09 08:36 UTC by zajca

přidaný RetryMiddleware všude kde vytváříme blob client

2020-11-09 08:41 UTC, ondrejhlavacek reviewed
Takhle jsem to +- nahackoval, ale errory typu https://keboola.slack.com/archives/C09U3R1J4/p1604906793051300 to bohužel nevyřešilo. Mám k tomu vytáhnout přesnej stack trace?

2020-11-09 08:48 UTC, ondrejhlavacek commented
@zajca 

![image](https://user-images.githubusercontent.com/497675/98518821-33763b00-2270-11eb-9cff-2a7708f752d6.png)

Tak tenhle retry to zřejmě nezachytí.

![image](https://user-images.githubusercontent.com/497675/98519153-a7b0de80-2270-11eb-986a-961b5c254cc9.png)

2020-11-09 09:03 UTC, zajca commented
á ještě je tam option:
```
$retryMiddleware = RetryMiddlewareFactory::create(
    RetryMiddlewareFactory::GENERAL_RETRY_TYPE,  // Specifies the retry logic
    3,  // Number of retries
    1000,  // Interval
    RetryMiddlewareFactory::EXPONENTIAL_INTERVAL_ACCUMULATION,  // How to increase the wait interval
    true  // Whether to retry connection failures too, default false
);
```

2020-11-09 15:18 UTC, ondrejhlavacek commented
Už na to Michal Hruška sype nějaký joby, tak uvidíme!

2020-11-09 16:18 UTC, ondrejhlavacek commented
![image](https://user-images.githubusercontent.com/497675/98566712-64299500-22af-11eb-93e1-01a34d12f307.png)

![image](https://user-images.githubusercontent.com/497675/98566838-8e7b5280-22af-11eb-8e19-26f46e5ad3e8.png)

Takže patrně bad luck :( Tohle by asi bylo potřeba odchytnout ručně :-(

2020-11-09 16:23 UTC, ondrejhlavacek commented
Tady ještě hlavička stack trace.

![image](https://user-images.githubusercontent.com/497675/98567323-16f9f300-22b0-11eb-8f3d-c5ab5650a3aa.png)

Já to tam kódim dost naslepo, kdyby tě napadlo, jak to tam nějak rozumně otryovat, můžu to ještě vyzkoušet. Co jako PoC nějaká pitomost typu
```php
            try {
                $blobClient->createBlockBlob(
                    $prepareResult['absUploadParams']['container'],
                    sprintf(
                        '%s%s',
                        $prepareResult['absUploadParams']['blobName'],
                        basename($slice)
                    ),
                    fopen($slice, 'r')
                );
            } catch (RequestException $e) {
                $blobClient->createBlockBlob(
                    $prepareResult['absUploadParams']['container'],
                    sprintf(
                        '%s%s',
                        $prepareResult['absUploadParams']['blobName'],
                        basename($slice)
                    ),
                    fopen($slice, 'r')
                );                
            }
```?

2020-11-09 16:32 UTC, ondrejhlavacek commented
Tak ten retryConnect asi nebude fungovat, očekává to `ConnectionException`, ale Gazl vyhodí `RequestException`

![image](https://user-images.githubusercontent.com/497675/98568426-61c83a80-22b1-11eb-8187-6a5df0b28623.png)

2020-11-13 14:14 UTC, ErikZigo requested changes
Včera jsem ověřil že ten základní RetryMiddleware od Microsoftu funguje a RequestException zachytává a dělá na němch retry. Defaultní počet pokusů je ale 3.

To číslo by chtělo zvýšit, protože očivindě i tak to někdy nezabere + by se hodil nějaký náš vastní RetryMiddlerware který by podporoval logování (viz komunikace na slacku)

2020-11-13 14:14 UTC, ErikZigo commented on src/Keboola/StorageApi/Downloader/AbsRetryMiddleware.php
> +            true
Tenhle parametr má vliv pouze na ConnectionExceptions, čili pokud ti nejde třeba vůbec internet.

2020-11-13 14:30 UTC, zajca commented
Initnul sem vlastní retry middleware, https://github.com/keboola/php-file-storage-utils/pull/1 logování za chvilku dokončím.

2020-11-20 13:40 UTC, zajca commented
PR sem předělal teď používá náš retry middleware, který dělá retry na všechno.

2020-11-20 14:39 UTC, zajca commented
> PR sem předělal teď používá náš retry middleware, který dělá retry na všechno.
> 
> // sakra tak to ještě musí jet na PHP 5.6

Tak sem udělal cop&paste toho middleware do clienta, nemá to podle mě váhu dělat downgrade té libky na 5.6 :/

2020-11-20 15:10 UTC, ondrejhlavacek approved these changes
tak snad :-)

2020-11-20 15:19 UTC, ErikZigo approved these changes

2020-11-20 16:55 UTC, merged