Test updating row changeDescription update changeDescription config
keboola/storage-api-php-client pull request #533
Opened 2020-11-24 17:46 UTC by fejjo

2020-11-24 19:10 UTC, tomasfejfar requested changes

2020-11-24 19:10 UTC, tomasfejfar commented on tests/Common/BranchComponentTest.php
> +
Přidej ještě prosím test na changedescription, když ji nenastavíš - tak co tam je ...

2020-11-24 20:14 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +
Pridal som ten test pre branch aware a aj do `ConfigurationRowTest`

2020-11-26 16:39 UTC, tomasfejfar reviewed
Nefunguje mi lokálně connection kvuli SQS chybě, tak to nemůžu otestovat

2020-11-26 16:39 UTC, tomasfejfar commented on tests/Common/ConfigurationRowTest.php
> +    public function testConfigurationRowUpdateChangeDescription()
Přijde mi zbytečné na to dělat novou metodu a dělat celý bootstrap jen kvuli otestování change description. Přidal bych to k existujícímu

2020-11-26 16:39 UTC, tomasfejfar commented on tests/Common/ConfigurationRowTest.php
> +    public function testConfigurationRowUpdateChangeDescription()
\Keboola\Test\Common\ComponentsTest::testComponentConfigRowUpdate

2020-12-01 12:01 UTC, tomasfejfar requested changes
Sorry, furt s tím nejsem OK :/

2020-12-01 12:01 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +        $this->assertEquals('Row main-1-1 added', $originalRow['changeDescription']);
Tady buď čtu špatně nebo tak chybí test toho, že se custom change description propíše do configuration z row. A chybí tu i ten, že configuration má default change description, pokud je u updatu row '' (ř. 1847)

2020-12-01 14:57 UTC, tomasfejfar approved these changes

2020-12-01 14:57 UTC, tomasfejfar commented on tests/Common/BranchComponentTest.php
> +        $this->assertEquals('Test change dev-1-row-1', $configurationAssociatedWithUpdatedRow['changeDescription']);
Tady přidán test na to, že se změněná custom description projeví u konfigurace

2020-12-01 14:57 UTC, tomasfejfar commented on tests/Common/BranchComponentTest.php
> +        $this->assertEquals('Row dev-1-row-1 changed', $configurationAssociatedWithUpdatedRow['changeDescription']);
Tady přidán test, že se default projeví u configurace

2020-12-01 14:57 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +        $this->assertEquals(
Tady se ověří custom description u configurace

2020-12-01 14:57 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +                ->setChangeDescription(null)
Tady jsem dal null, který víc odpovídá tomu, co by tam bylo kdybych to nenastavil.

2020-12-01 14:57 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +        $this->assertEquals('Row main-1-1 changed', $configurationAssociatedWithUpdatedRow['changeDescription']);
Assert, že se default propíše ke konfiguraci.

2020-12-02 07:43 UTC, fejjo commented
presiel som to vcera a vyzeralo to dobre.

2020-12-02 07:43 UTC, merged