Init PR template
keboola/storage-api-php-client pull request #536
Opened 2020-11-25 13:22 UTC by ujovlado

Changes:

- Adding PR template

---

Kazdy novy PR potom bude mat checklist, co treba spravit

2020-11-25 13:57 UTC, tomasfejfar approved these changes
Přijde mi to jako zlepšení.

2020-11-25 14:02 UTC, fejjo approved these changes
za mna ok, mozeme casom pridavat dalsie veci do check listu ak na nieco narazime.

2020-11-25 14:06 UTC, zajca commented
To after review mě moc nedává smysl, BC v public metodách neděláme a po review je to asi k ničemu, mělo by byt součástí review zajistit aby nikdo BC neudělal.

2020-11-25 14:28 UTC, tomasfejfar commented
BC děláme AFAIK. Tak se taky stalo, že jsme na verzi 10 a nejsme furt na v1.

2020-11-25 14:38 UTC, zajca commented
> BC děláme AFAIK. Tak se taky stalo, že jsme na verzi 10 a nejsme furt na v1.

No v10 bude slavit 3roky za chvilku, tak jestli bude jednů za 3 a víc roků ten checkbox relevantní mě nepřijde docela zbytečné.

2020-11-25 14:40 UTC, ujovlado commented
To co sa ma stat po mergi je imho "zbytocne" mat v checkliste ... ide tam skor o to, co ma obsahovat ten PR.

Navrhoval by som:

```
Before asking for review:

- [ ] New client method has tests
- [ ] Apiary file is updated
- [ ] Declare if there is a BC break or not (will affect next release of a client)
```

2020-11-25 14:43 UTC, ujovlado commented
Priklad:

![Screenshot 2020-11-25 at 15 43 04](https://user-images.githubusercontent.com/419849/100242312-f29b4900-2f34-11eb-9404-33d2c408abae.png)

2020-11-25 14:45 UTC, ujovlado commented
Je jediny dovod preco to chcem, nech to mam na ociach ... t.j. hned pocas vytvarania PR si uvedomim ci som na nieco nezabudol ... a pripomenie mi to sa na chvilku zamysliet (to co okrajovo spomina Erik)

2020-11-25 14:46 UTC, ujovlado commented
Dajme tam proste nejaku verziu a casom sa to doladi podla toho ako sa to bude pouzivat

2020-11-26 14:43 UTC, ErikZigo requested changes
Udělej to takhle to mi přijde v pohodě.
https://github.com/keboola/storage-api-php-client/pull/536#issuecomment-733747180

> Dajme tam proste nejaku verziu a casom sa to doladi podla toho ako sa to bude pouzivat
Přesně tak.

2020-11-26 14:44 UTC, ujovlado commented
ok, idem to upravit a poslem to tam - to sa da doladit kedykolvek, nemusime to riesit 2 dni :)

2020-11-26 14:57 UTC, ujovlado commented
@ErikZigo tak este to chce tvoj approve 😇

2020-11-26 15:05 UTC, ErikZigo commented
No ja jsem myslel ze je to na review celymu tymu a ne konkretne kazdymu. Tak jsem to nechal lezet. :-)

2020-11-26 15:05 UTC, ErikZigo approved these changes
👍

2020-11-26 15:06 UTC, ujovlado commented
JO, ale dal si "request changes", takze cakalo explicitne na tvoje ANO 👰

2020-11-26 15:06 UTC, merged