KBC-1108 branch aware event detail
keboola/storage-api-php-client pull request #540
Opened 2020-11-29 20:35 UTC by fejjo

Jira: KBC-1181
Main PR: https://github.com/keboola/connection/pull/2920
Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated - nothing to update
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2020-11-30 13:48 UTC, ErikZigo requested changes
Tahle změna určitě potřebuje apiary filu. To že tam teď nemáme detail eventy je nějaký bug. Musí se tam doplnit.

2020-11-30 13:54 UTC, fejjo commented
> Tahle změna určitě potřebuje apiary filu. To že tam teď nemáme detail eventy je nějaký bug. Musí se tam doplnit.

Upravim myslel som si ze to tam nebolo schvalne

2020-11-30 14:17 UTC, tomasfejfar commented on tests/Common/BranchEventsTest.php
> +        // event for development branch dispatched
Asi jen upravit komentář

2020-11-30 17:06 UTC, fejjo commented on tests/Common/BranchEventsTest.php
> +        $this->assertSame('dev-branch-'.$branch['id'], $createConfigEventDetail['objectId']);
trochu nestastne pomenovanie configId :) https://github.com/keboola/storage-api-php-client/pull/540/commits/d66ac597ef82f72086af6ccfab85d483e24ee166

2020-11-30 17:06 UTC, fejjo commented on tests/Common/BranchEventsTest.php
> +        // event for development branch dispatched
Upravil som

2020-11-30 18:41 UTC, tomasfejfar commented on tests/Common/BranchEventsTest.php
> +        $this->assertSame('dev-branch-'.$branch['id'], $createConfigEventDetail['objectId']);
Haha :D 👍

2020-12-01 08:22 UTC, fejjo commented
Pridal som dokumentaciu a uprvil komentar

2020-12-01 17:29 UTC, tomasfejfar commented
Viděl jsem, že erik reviewoval ten connection PR k tomu, tak se odebírám z review...

2020-12-03 11:40 UTC, ErikZigo approved these changes

2020-12-03 16:41 UTC, merged