KBC-1138: Add test for increments versions of config and config rows
keboola/storage-api-php-client pull request #541
Opened 2020-11-30 16:32 UTC by fejjo

Jira: KBC-1138

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2020-12-03 06:57 UTC, natocTo commented on tests/Common/BranchComponentTest.php
>          // updated rows should have version 1, if rows weren't updated version should be 0
Super drobnost, tento komentář ještě popisuje to staré chování.

2020-12-03 08:21 UTC, fejjo commented
Build vyfailoval na nejakej hluposti na travise, inac by to bolo normalne zelene

2020-12-04 10:03 UTC, fejjo commented
@tomasfejfar sorry este som tam nieco pridaval a zabudol som vypnut PR na review uz je to ale imho ok

2020-12-04 13:48 UTC, tomasfejfar reviewed
Sorry, nevšimnul jsem si, že už na to kouká erik, tak posílám jen svoje poznámky

2020-12-06 16:48 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $configFromMain = $branchComponents->getConfiguration($componentId, 'main-1');
Pridal som riadok 250

2020-12-06 16:48 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $configFromMain = $branchComponents->getConfiguration($componentId, 'main-1');
262

2020-12-06 16:48 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $configFromMain = $branchComponents->getConfiguration($componentId, 'main-1');
278

2020-12-06 18:31 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $this->assertEquals('updated', $currentVersion['changeDescription']);
riadok 250

2020-12-06 18:33 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $this->assertEquals('copied', $currentVersion['changeDescription']);
UIcko sa nebude riadit podla tych `changeDescription` https://keboola.atlassian.net/browse/KBC-1138?focusedCommentId=24469 ale podla `created` a `versionCreated`

2020-12-06 18:33 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $this->assertEquals('Copied from default branch configuration "Main 1" (main-1) version 2', $currentVersion['changeDescription']);
UIcko sa nebude riadit podla tych `changeDescription` https://keboola.atlassian.net/browse/KBC-1138?focusedCommentId=24469 ale podla `created` a `versionCreated`

2020-12-07 10:25 UTC, tomasfejfar requested changes
Failuje \Keboola\Test\Common\ComponentsTest::testChangeDescription

2020-12-07 10:44 UTC, fejjo commented
<img width="1504" alt="Screenshot 2020-12-07 at 11 43 34" src="https://user-images.githubusercontent.com/6448364/101341491-72a0a780-3881-11eb-9e5b-7e2ca4525e62.png">
@tomasfejfar co ti to pise za chybu ja sa obavam ze to sposobuje to na co prisiel Erik  https://keboola.atlassian.net/browse/KBC-1151

2020-12-07 11:53 UTC, tomasfejfar commented
Bude vyřešeno v rámci https://github.com/keboola/connection/pull/2950 (KBC-1151)

2020-12-07 12:11 UTC, fejjo commented
Pridal som este jeden test na `Configuration updated` co pisal Erik

2020-12-07 14:04 UTC, fejjo commented
U toho main PR som nepushol zatial ten rebase ktory fixuje tu chybu  keboola/connection#2950 (KBC-1151), ja len aby sa niekto necudoval keby nahodou zacal robit review a neslo by to:)

2020-12-08 08:05 UTC, tomasfejfar commented
KBC-1151 je v masteru ;)

2020-12-08 08:06 UTC, fejjo commented
rebasol som main PR

2020-12-08 12:23 UTC, tomasfejfar requested changes
Spustil jsem i nějaké přidružené testsuites. Předtím jsem procházel logickou strukturu těch testů a bylo to OK. Ta poslední úprava od erika je v branchi otestovaná taky. Jediné co mi chybí je assert na default change description konfigurace v ComponentsTest.

2020-12-08 16:06 UTC, fejjo commented
> Jediné co mi chybí je assert na default change description konfigurace v ComponentsTest.

Toto mi nieje uplne jasne, v main PR vobec neupravujem tie main configurace takze som na povodne testy neshal,  naviac ako to spravne chapem co chces otestovat tak tie testy tam su napr na riadku 830, 568 alebo pri row 1864, ale mozno som to pochopil blbo. :)

2020-12-08 18:23 UTC, tomasfejfar approved these changes
Nějak mi nedošlo, že jsem tu změnu changeDescription v mainu neviděl v tom druhém PR. Přijde mi divné, že se chová jinak branch a jinak main. Ale to není problém tohohle PR asi..

2020-12-08 18:24 UTC, tomasfejfar commented
https://keboola.atlassian.net/browse/KBC-1156

2020-12-09 08:14 UTC, fejjo commented
rebase

2020-12-09 09:00 UTC, merged