Run ComminPart2 paralel
keboola/storage-api-php-client pull request #553
Opened 2021-01-06 18:27 UTC by fejjo

Jira: KBC-XXX

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-01-08 11:10 UTC, ErikZigo commented
jdu na to

2021-01-08 11:16 UTC, fejjo commented
Jo sry zabudol som to prepnut ;)

2021-01-08 11:19 UTC, ErikZigo commented on phpunit.xml.dist
> +		<directory>tests/Backend/CommonPart2</directory>
Tím že ty testy přidáš do paratest suity tak bys je měl odebrat z té původní. Jednak tam jsou zbytešně a navíc by dodrbaly ty testovací projekty který s paralelníma testama nepočítají.

2021-01-08 11:22 UTC, ErikZigo requested changes
Asi bysme si nad tím měli zavolat.

2021-01-12 12:37 UTC, zajca approved these changes
LGTM fičí to. 
Co mě sere je jen to, že paratest bere risky testy jako ERROR

![image](https://user-images.githubusercontent.com/180148/104313171-ee70be00-54d7-11eb-878b-2781fd8add24.png)

Docela sa divím, že je pak exit code 0
Vypadá to, že je to fixnuté v novějším paratestu https://github.com/paratestphp/paratest/issues/282
Zkotroloval sem si, že to fakt vrací 0 když sů špatně ty risky a něco jiného když je tam fakt chyba :+1:

2021-01-18 08:08 UTC, fejjo commented
rebase

2021-01-18 14:38 UTC, merged