KBC-1295 Add test for scenario when config version should not be incr…
keboola/storage-api-php-client pull request #577
Opened 2021-02-24 15:58 UTC by jirkasemmler

Jira: KBC-1295

New test for https://github.com/keboola/connection/pull/3076 . Checking that if you update a Configuration with the same data (no change) it wont increase version.

2021-02-25 14:36 UTC, fejjo requested changes
Vzhladom ktomu, ze sa verzie testuju v teste hned nad `\Keboola\Test\Common\ConfigurationRowsSortOrderTest::testReorderVersionIncrease` by som to pridal do toho povodneho testu. V `setUp` metode sa na zaciatku testu vzdy robi nejaky clenaup, a pride mi teda zbytocne to co si v tom teste na-setupujes zahodit a hned vytvarat to iste. Takze by som to pridal do toho povodneho a trochu upravil nazov testu na nieco co bude evokovat, ze sa tam testuje aj varianta ze ked nezmenim nic, nezmeni sa mi ani verzia, imho to tam malo byt uz davno :/ Plus teda pridat este test do `BranchComponentTest` jak som pisal v PR v KBC repe. Plus som napisal este nejake poznamocky k testom co si pisal. :)

2021-02-26 14:26 UTC, jirkasemmler commented
@fejjo done, ten novej test jsem revertnul a dal to do puvodniho testu. 

Ale v pripade tests/Common/BranchComponentTest.php jsem test udelal novej, protoze uplne nechci strkat prsty do te obri 800 lajnove test metody. Ta by se mela imho rozdelit podle UC.

2021-02-26 16:15 UTC, fejjo commented
> @fejjo done, ten novej test jsem revertnul a dal to do puvodniho testu.
> 
> Ale v pripade tests/Common/BranchComponentTest.php jsem test udelal novej, protoze uplne nechci strkat prsty do te obri 800 lajnove test metody. Ta by se mela imho rozdelit podle UC.

Urobilo sa

2021-02-26 16:40 UTC, fejjo commented
@jirkasemmler takto je to za mna dobre pridal som tam este jeden commit https://github.com/keboola/storage-api-php-client/pull/577/commits/b809a354ce152d2f9f7d585965496e7eb0c75ea2 kde sa este len skontroluje ta verzia pred updatom kde nastavujes ten rowsSortOrder. Tak nemas nic proti tak sa to moze mergnut.

2021-02-26 16:40 UTC, fejjo approved these changes
👌

2021-03-01 10:23 UTC, merged