KBC-1336
keboola/storage-api-php-client pull request #583
Opened 2021-03-05 10:49 UTC by zajca

Jira: KBC-1336 
KBC: https://github.com/keboola/connection/pull/3102

Before asking for review make sure that:

- [x] New client method(s) has tests
- [] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2021-03-10 12:40 UTC, fejjo requested changes
Jedna drobnost

2021-03-10 12:40 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +        $componentsApi->rollbackConfiguration('wr-db', $configurationV1['id'], 2);
Otestuj prosim este ak zadam custom `changeDescription`

2021-03-17 11:11 UTC, zajca commented on tests/Common/BranchComponentTest.php
> +        $componentsApi->rollbackConfiguration('wr-db', $configurationV1['id'], 2);
přidáno

2021-03-17 11:31 UTC, fejjo approved these changes
👍

2021-03-17 11:39 UTC, merged