Erik kbc 1353
keboola/storage-api-php-client pull request #596
Opened 2021-03-30 05:53 UTC by ErikZigo

Jira: KBC-XXX

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-03-30 11:55 UTC, ErikZigo commented on src/Keboola/StorageApi/Client.php
>      public function refreshToken($tokenId = null)
Tohle jediné tady zůstane v příštím major releasu. Půjde ale přes to refreshnout jen aktuální token v clientovi.

2021-03-31 10:12 UTC, jirkasemmler requested changes
asi cajk, jen par drobnosti. Doporucil bych ale jeste palecek od nekoho z rady starsich

2021-03-31 11:57 UTC, ErikZigo commented on src/Keboola/StorageApi/Tokens.php
> +    /**
Ne, kvuli starym transformacim, orchestratoru a podobne udrzujeme klienta kompatibilniho s PHP 5

2021-03-31 12:01 UTC, ErikZigo commented on src/Keboola/StorageApi/Tokens.php
> +        return $this->client->apiGet("tokens/{$id}");
Jako muzu no :-) Jsem to jen prekopiroval.
Konvence na tohle nemame, alespon o nich nevim.

2021-04-01 09:59 UTC, ErikZigo commented on src/Keboola/StorageApi/Tokens.php
> +    public function getToken($id)
Upraveno

2021-04-01 09:59 UTC, ErikZigo commented on src/Keboola/StorageApi/Tokens.php
> +        return $this->client->apiGet("tokens/{$id}");
Upraveno

2021-04-01 11:43 UTC, zajca approved these changes
LGTM

2021-04-01 11:57 UTC, jirkasemmler approved these changes

2021-04-01 12:01 UTC, ErikZigo commented
@jirkasemmler muzes na to juknout? review od zajci je hotove ale visi tu ten tvuj change request. dismiss review ti davat nechci :-)

2021-04-03 08:08 UTC, merged