Jirka kbc 1513 create typed table doc
keboola/storage-api-php-client pull request #616
Opened 2021-05-14 10:13 UTC by fejjo

Jira: KBC-1513

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-05-17 14:09 UTC, fejjo commented on apiary.apib
> +
Creates a new table in a bucket asynchronously by definition of table.

2021-05-17 14:09 UTC, fejjo commented on apiary.apib
> +       + name
name ma byt required a string

2021-05-17 14:10 UTC, fejjo commented on apiary.apib
> +            + type (required) - datatype of this column, choose one from https://bit.ly/3uZjN60
string

2021-05-17 14:13 UTC, fejjo commented on apiary.apib
> +    + primaryKeysNames[] (string) - has to be subset of column names
Toto moze byt optional?

2021-05-17 14:14 UTC, fejjo commented on apiary.apib
> +
PRidal by som nejaku veticku co ten endpoint robi

2021-05-17 14:16 UTC, fejjo commented on apiary.apib
> +                            "length": "10",
```suggestion
                            "length": null,
```
pre int to nieje validna hodnota
<img width="665" alt="Screenshot 2021-05-17 at 16 16 27" src="https://user-images.githubusercontent.com/6448364/118503787-3c6a2c80-b72b-11eb-9a55-a81e1d3a1c24.png">

2021-05-17 14:32 UTC, jirkasemmler commented on apiary.apib
> +    + primaryKeysNames[] (string) - has to be subset of column names
optional ne, ale prazdne ano, doplnim

2021-05-18 06:14 UTC, zajca commented on apiary.apib
> +                + HASH - requires just on column in `distributionColumnsNames`
```suggestion
                + HASH - requires exactly ono column in `distributionColumnsNames`
```

2021-05-24 06:44 UTC, zajca requested changes
Je to cajk, ale response nesedí, nesedí params ani název operace.

2021-05-24 06:44 UTC, zajca commented on apiary.apib
> +        }
Ta json response neodpovídá tomu co reálně ten endpoint vrací.
```suggestion
        {
   "id":255,
   "status":"waiting",
   "url":"https:\/\/localhost:8700\/v2\/storage\/jobs\/255",
   "tableId":null,
   "operationName":"tableDefinitionCreate",
   "operationParams":{
      "name":"test",
      "columns":[
         {
            "name":"test",
            "definition":{
               "type":"INT",
               "nullable":true
            }
         }
      ],
      "distribution":{
         "type":"ROUND_ROBIN",
         "distributionColumnsNames":[
            
         ]
      },
      "queue":"main"
   },
   "createdTime":"2021-05-24T08:40:47+0200",
   "startTime":null,
   "endTime":null,
   "runId":"1480",
   "results":null,
   "creatorToken":{
      "id":"2260",
      "description":"devel+test-common_admin@keboola.com"
   },
   "metrics":{
      "inCompressed":false,
      "inBytes":0,
      "inBytesUncompressed":0,
      "outCompressed":false,
      "outBytes":0,
      "outBytesUncompressed":0
   }
}
```

2021-05-24 09:15 UTC, jirkasemmler commented
@zajca opraveno, jeste jsem to potunil aby to opravdu odpovidalo

2021-05-24 09:26 UTC, zajca approved these changes
Cajk :heavy_check_mark:

2021-05-24 09:32 UTC, merged