KBC-1721 delete devBranch configuration
keboola/storage-api-php-client pull request #646
Opened 2021-08-11 09:35 UTC by martinjunger

Jira: KBC-1721

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2021-08-11 14:01 UTC, fejjo requested changes

2021-08-11 14:01 UTC, fejjo commented on tests/Common/BranchComponentTest.php
> +            $this->assertSame('In development branches is not posible delete configuration from trash.', $e->getMessage());
```suggestion
            $this->assertSame('In development branches is not possible delete configuration from trash.', $e->getMessage());
```

2021-08-11 18:00 UTC, martinjunger commented on apiary.apib
> +[restore deleted](#reference/component-configurations/manage-configs/restore-deleted-config) configurations.
Jasně, zapomněl jsem je upravit. Dík

2021-08-12 07:51 UTC, martinjunger commented on apiary.apib
> +[restore deleted](#reference/component-configurations/manage-configs/restore-deleted-config) configurations.
Opraveno. Ty reference jsou spatne uz cca 4 roky 🤔

2021-08-12 09:35 UTC, fejjo approved these changes
lgtm, este som pridal nieco do testov https://github.com/keboola/storage-api-php-client/pull/646/commits/084034accab98c2cf343e64693701f5e7b156aa6 ak ti to pride v pohode tak by som to asi squashol na nejake rozumne commity nech tam niesu tie fixupy a mergol. Nezabudni ze sa ma aj tagnut nova verzia klienta

2021-08-13 10:42 UTC, merged