KBC-1720 delete devBranch configuration row
keboola/storage-api-php-client pull request #648
Opened 2021-08-13 16:28 UTC by martinjunger

Jira: KBC-1720

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2021-08-16 09:31 UTC, martinjunger commented
Rebasnuto.

2021-08-16 11:37 UTC, ErikZigo requested changes
Měl bys testovat že při smazání row se zvýší číslo verze konfigurace. Podobně jako je to v testu pro main branch `testComponentConfigRowDelete`.

A ještě bych udělal obdobu testu `testChangeDescription` kde se testuje ta propagace change description

2021-08-16 13:58 UTC, martinjunger commented
Pridano.
> Měl bys testovat že při smazání row se zvýší číslo verze konfigurace. Podobně jako je to v testu pro main branch `testComponentConfigRowDelete`.

Pridal jsem do testu jen changeDescription pro delete. Test pro vsechny ty akce si necham bokem a zitra rano dodelam ve zvlastnim PR.
> A ještě bych udělal obdobu testu `testChangeDescription` kde se testuje ta propagace change description

2021-08-16 14:57 UTC, ErikZigo commented on tests/Common/BranchComponentTest.php
> +        $branchComponents->deleteConfigurationRow($componentId, 'main-1', 'main-1-row-1', $deleteRowChangeDescription);
Idealne kdybys zalozil 2 row a jednu zkusil smazat bez change description a druhou s.

2021-08-17 05:05 UTC, martinjunger commented on tests/Common/BranchComponentTest.php
> +        $branchComponents->deleteConfigurationRow($componentId, 'main-1', 'main-1-row-1', $deleteRowChangeDescription);
OK, pridano.

2021-08-17 09:02 UTC, martinjunger commented
Koukal jsem, ze `changeDescription` se uz testuje v ostatnich testech, tak to necham pridany jen k tomu `delete config row`, pac by se to potom duplikovalo.
> Pridal jsem do testu jen changeDescription pro delete. Test pro vsechny ty akce si necham bokem a zitra rano dodelam ve zvlastnim PR.
> 
> > A ještě bych udělal obdobu testu `testChangeDescription` kde se testuje ta propagace change description

2021-08-17 10:40 UTC, ErikZigo approved these changes

2021-08-17 12:29 UTC, merged