KBC-1825 fix data preview with numeric column type
keboola/storage-api-php-client pull request #677
Opened 2021-09-03 18:13 UTC by fejjo

Jira: KBC-XXX

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-09-07 09:24 UTC, jirkasemmler commented on tests/Backend/Exasol/TableDefinitionOperationsTest.php
> +        $tableDefinition = [
imho bych trochu rozsiril ty typy co tam zkousime. Dal bych jednoho zastupce z kazdeho BaseTypu a pak vsechny divnotypy co identifikujeme jako string (binary, unique, money...)

2021-09-07 09:25 UTC, jirkasemmler requested changes
imho musime dotestovat vice tech typu, viz conenction

2021-09-07 09:25 UTC, jirkasemmler commented on tests/Backend/Exasol/TableDefinitionOperationsTest.php
> +        $tableDefinition = [
sorry, strcil jsem to k EXA ale melo to jit k Synapse tride. Ale to je ve vysledku jedno

2021-09-07 17:41 UTC, fejjo commented
Divno typy pridane diky :)

2021-09-08 08:15 UTC, jirkasemmler approved these changes
lgtm

2021-09-08 08:40 UTC, merged