KBC-1725 copy devBranch configuration: update doc
keboola/storage-api-php-client pull request #681
Opened 2021-09-15 10:44 UTC by martinjunger

Jira: KBC-1725

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2021-09-16 10:33 UTC, tomasfejfar requested changes
Chybí otestovat chování, pokud má konfigurace rows. 

* mám konfiguraci (v1)
* přidám configrow1 (v2) 
* upravím configrow1 (v3)
* přidam configrow2 (v4)
* smažu prvni configrow (v5)
* udělám config z v2 a čekám, že má jen configrow1 v původní verzi

2021-09-16 11:26 UTC, tomasfejfar commented
⬆️ sorry, nenapsal jsem to jasně. Šlo mi o to, že v branchi se jinak chovají verze rows a chtěl bych v tom testu vidět i to, že to funguje a nerestorne to poslední verzi té row, ale tu verzi, kterou má...

2021-09-17 14:23 UTC, martinjunger commented
> ⬆️ sorry, nenapsal jsem to jasně. Šlo mi o to, že v branchi se jinak chovají verze rows a chtěl bych v tom testu vidět i to, že to funguje a nerestorne to poslední verzi té row, ale tu verzi, kterou má...

Upraveno.

2021-09-17 15:10 UTC, tomasfejfar approved these changes
Funguje jak má! :)

2021-09-20 10:05 UTC, merged