KBC-1977 initEvent in callback WIP
keboola/storage-api-php-client pull request #706
Opened 2021-11-01 15:45 UTC by martinjunger

Jira: KBC-1977

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2021-11-09 15:03 UTC, fejjo commented
👁️

2021-11-09 15:35 UTC, fejjo reviewed
Pride mi to takto celkom v pohode, testy mi na tom prechadzaju uvidime co Tomas, hovoril si ze mu vadila ta zmena protected=>public metod tak by ma zaujimalo preco

2021-11-09 15:36 UTC, fejjo commented
Potom teda pridat upravu vsetkych testov co by to mali pouzivat.

2021-11-09 16:52 UTC, martinjunger commented
> Potom teda pridat upravu vsetkych testov co by to mali pouzivat.

@fejjo Nahrazeno ve vsech testech. Puvodni callback metody smazany.

2021-11-09 19:21 UTC, tomasfejfar reviewed
Nepřijde mi to vůbec špatný.

2021-11-09 19:21 UTC, tomasfejfar commented on tests/ClientProvider/ClientProvider.php
> +    public function getDevBranchClient($config = [], $useExistingBranch = false)
tady se mi akorát furt nelíbí ten flag parametr, ale couž, je to detail :)

2021-11-09 19:21 UTC, tomasfejfar commented on tests/ClientProvider/ClientProvider.php
> +    public function getDevBranchClient($config = [], $useExistingBranch = false)
Vůbec by mě neurazilo, kdyby ta metoda neřešila branch a prostě chtěla branchId. Co si pamatuju, tak to ničemu nevadí. Prostě Single Responsibility Principle - řeší to klienta, umí to řešit jen klienta. Chceš tam řešit branche, tak se nejdřív zeptej něčeho co řeší branche a sem dej jen ten výsledek :) 

V set up metodě by sis to explicitně zavolal "createBranchForTestCase" a poslal bys to sem. 
V optimálním scénáři "klient provider" providuje clienta a nezakládá branche. Od to by byl "BranchProvider" nebo tak něco - ten by ti zas mohl buď dát existující branch nebo založit novou. 

Ale zas to nechci zbytečně hrotit :)

2021-11-09 19:21 UTC, tomasfejfar commented on tests/StorageApiTestCase.php
> +    public function getDefaultBranchId(self $that)
Tohle mě vůbec neuráží, nějak si nepamatuju, kde jsem to rozporoval... ale samozřejmě by to mohlo být v branch provideru :)

2021-11-16 16:06 UTC, martinjunger commented
Pridan test pro ClientProvider.

2021-11-17 09:50 UTC, tomasfejfar commented
Ten clientProvider test jsem čekal něco jako:

```php
    public function testCreateClientForCurrentTest()
    {
        $clientMock = $this->createMock(Client::class);
        $branchAwareClientMock = $this->createMock(BranchAwareClient::class);
        $testCase = $this->getMockBuilder(StorageApiTestCase::class)
            ->disableAutoReturnValueGeneration()
            ->getMock();
        $testCase->method('usesDataProvider')->willReturn(false);
        $testCase->method('getDefaultClient')->willReturn($clientMock);
        $testCase->method('getDefaultBranchId')->willReturn(7);
        $testCase->method('getBranchAwareDefaultClient')->willReturn($branchAwareClientMock);
        $provider = new ClientProvider($testCase);
        $client = $provider->createClientForCurrentTest();
        $this->assertInstanceOf(Client::class, $client);
        $client = $provider->createBranchAwareClientForCurrentTest();
        $this->assertInstanceOf(BranchAwareClient::class, $client);
    }
```

Myšleno aby otestoval, že s nějakými vstupy to vrátí nějaké výstupy. Ale tak jak je to napsané, tak se to ukrutně těžko mockuje :(

2021-11-17 09:52 UTC, tomasfejfar commented
Ten test co tam je teď je vlastně integrační (jestli to funguje s reálným test casem a setupne se to správně v setUp), což je asi OK, ale přijde mi teda dost nepřehledný a docela nepochopitelný.

2021-11-17 12:16 UTC, tomasfejfar requested changes
Opravit tu __CLASS__ je imho jediný must-have fix...

2021-11-17 12:16 UTC, tomasfejfar commented on tests/Common/ConfigurationRowTest.php
> +                'X-StorageApi-Token' => $this->client->getTokenString(),
Tohle byl dobrej punk naming :D Zásadně lepší takhle 👍

2021-11-17 12:16 UTC, tomasfejfar commented on tests/Common/SearchComponentsConfigurationsTest.php
> +        $this->client = $clientProvider->createBranchAwareClientForCurrentTest();
Nejsem si jistej, ale nemělo by tady dycky bejt normální get client? Takhle i pokud bude "defaultBrnach" tak to dostane branchovaného klienta, ne?

2021-11-17 12:16 UTC, tomasfejfar commented on tests/Common/SearchComponentsConfigurationsTest.php
> +        $this->client = $clientProvider->createBranchAwareClientForCurrentTest();
Ale vlastně tam je to jen skrz branch, tak nic, tak je to OK ;)

2021-11-17 12:16 UTC, tomasfejfar commented on tests/StorageApiTestCase.php
> +    public function deleteBranchesByPrefix(DevBranches $devBranches, $branchPrefix)
Tohle jak jsme se bavili - mnohem radši bych to viděl v nějakém izolovaném "branch provideru" ale co už :)

2021-11-17 12:16 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +        $this->client = $this->clientProvider->createClientForCurrentTest();
Ještě na zvážení, jestli ho nepojmenovat "clientFromProvider" aby byl líp vizuálně oddělený od "_client"

2021-11-18 11:43 UTC, tomasfejfar requested changes
Chybí ještě test na getDevBranchName

2021-11-18 14:02 UTC, jirkasemmler commented
mam jednu prosbu (nevim jak moc je resitelna, nesnazil jsem se uplne ponorit...), neslo by ty datasety pojmenovat? bylo super jak u puvodni implementace byl "defaultBranch" a "devBranch" (nebo tak neco...) @martinjunger 
![image](https://user-images.githubusercontent.com/13363655/142429697-d918d381-1454-4d0f-84fd-c316b19c59e1.png)

2021-11-18 15:04 UTC, martinjunger commented
> mam jednu prosbu (nevim jak moc je resitelna, nesnazil jsem se uplne ponorit...), neslo by ty datasety pojmenovat? bylo super jak u puvodni implementace byl "defaultBranch" a "devBranch" (nebo tak neco...) @martinjunger ![image](https://user-images.githubusercontent.com/13363655/142429697-d918d381-1454-4d0f-84fd-c316b19c59e1.png)

Jasne, pojmenuju.

2021-11-18 15:04 UTC, martinjunger commented
> Chybí ještě test na getDevBranchName

Pridano.

2021-11-18 15:07 UTC, martinjunger commented on tests/Common/ComponentsEventsTest.php
> +    public function testConfigurationDelete($clientName)
Jo, jsem uz nad tim premyslel, ale zrovna `type` me bud nenapadl, nebo uz nevim :)

2021-11-18 15:16 UTC, martinjunger commented on tests/Common/ComponentsEventsTest.php
> +        if ($clientName === ClientProvider::DEV_BRANCH) {
To uz mi prijde zbytecne ukecany.

2021-11-18 15:17 UTC, martinjunger commented on tests/ClientProvider/ClientProvider.php
> +        $devBranch = new DevBranches($this->getDefaultClient());
Upraveno na `$devBranches`. Dik.

2021-11-19 10:21 UTC, tomasfejfar approved these changes
Prošel jsem ty poslední změny a za mě OK. Chtěl jsem si pustit ještě ty testy k tomu, ale jede to ukrutně pomalu.

2021-11-19 10:33 UTC, martinjunger commented on tests/StorageApiTestCase.php
> +        // temporary fallback
Dokud nebude vsude novy ClientProvider - uz je. Fixnuto.

2021-11-19 11:08 UTC, merged