KBC-1726 consolidate DevBranch tests for components
keboola/storage-api-php-client pull request #718
Opened 2021-11-16 09:08 UTC by jirkasemmler

Jira: KBC-1726

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-11-17 12:22 UTC, tomasfejfar commented
Tohle bude confliktit epicky s tou branchí co má @martinjunger :(

2021-11-17 12:28 UTC, tomasfejfar approved these changes
Akorát pokud to půjde, tak bych revertnul ty "kosmetické" změny, protože z toho se martin zblázní, až to bude při rebasu rozmotávat...

2021-11-17 12:28 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> -        $componentsApi = new Components($getClient($this));
Proč?

2021-11-17 12:28 UTC, tomasfejfar commented on tests/Common/ComponentsTest.php
> +        $componentsApi = new Components($getClient($this));
Jako určitě lepší naming, ale IMHO zbytečný diff který udělá konflikt

2021-11-18 13:24 UTC, jirkasemmler commented
kosmeticke zmeny revertnu, dohodli jsme se s @martinjunger ze to postavim na te jeho vetvi . Jeho upravy jsou temer stabilni a zmena moji logiky docela trivialni, takze bude asi jednodussi, kdyz budu rebasovat ja. 

FYI @tomasfejfar

2021-11-19 10:50 UTC, martinjunger commented
👁️

2021-11-19 11:40 UTC, martinjunger requested changes
Vypada to OK, jen chybi rebase.

2021-11-19 12:33 UTC, martinjunger approved these changes
OK

2021-11-19 13:57 UTC, merged