Test async share unshare bucket
keboola/storage-api-php-client pull request #733
Opened 2021-11-30 15:58 UTC by fejjo

Jira: KBC-2237

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2021-12-01 07:54 UTC, tomasfejfar requested changes

2021-12-01 07:54 UTC, tomasfejfar commented on src/Keboola/StorageApi/Client.php
> +    public function shareBucket($bucketId, $options = [], $async = false)
Tohle by mělo být součást options. Je to tak u jiných endpointů (např. workspace drop)

2021-12-01 07:54 UTC, tomasfejfar commented on tests/Backend/Mixed/SharingTest.php
> +        ];
Co když budeme chtít přidat další věc k otestování? Budeme muset myslet na to, abysme přidali sync i asynch verzi. Bylo by IMHO lepší udělat `foreach ([true, false] as $async)` a v něm yieldovat

2021-12-01 07:54 UTC, tomasfejfar commented on tests/Backend/Mixed/StorageApiSharingTestCase.php
> +        ];
To samé tady

2021-12-02 13:06 UTC, zajca approved these changes
Jo vypadá to kůl, Tomášovy připomínky sů vypořádané. Testy prošly, ověřil sem v PT že sa fakt pustili. Něco sem si pustil lokálně. Každopádně sem nestartoval RS abych pustil všecko. (Bože ty shared testy v mixed backend suitě sů peklo)

2021-12-02 13:07 UTC, zajca commented
> Jo vypadá to kůl, Tomášovy připomínky sů vypořádané. Testy prošly, ověřil sem v PT že sa fakt pustili. Něco sem si pustil lokálně. Každopádně sem nestartoval RS abych pustil všecko. (Bože ty shared testy v mixed backend suitě sů peklo)

Ještě mě napadá, že to samé máme ještě v `MixedSnowflakeExasol` a `MixedSnowflakeSynapse` ale nepřipadá mě důležité aby to bylo všude.

2021-12-05 17:03 UTC, fejjo commented
Dokumentaciu som upravil v separatnom PR, tu som este musel upravit update sharovania aby bol ten async parameter v url tak ako to mame u vsetkeho

2021-12-06 07:46 UTC, zajca approved these changes

2021-12-06 07:59 UTC, fejjo commented
rebase

2021-12-06 08:27 UTC, merged