KBC-2410 branch metadata final
keboola/storage-api-php-client pull request #765
Opened 2022-02-18 16:53 UTC by martinjunger

Jira: KBC-2410
Connection: https://github.com/keboola/connection/pull/3601

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2022-02-21 08:59 UTC, tomasfejfar commented
👀

2022-02-21 09:38 UTC, tomasfejfar requested changes

2022-02-21 09:38 UTC, tomasfejfar commented on tests/Common/BranchMetadataTest.php
> +        $this->assertNotSame($metadata[0]['timestamp'], $branchMetadata[0]['timestamp']);
Tohle je IMHO špatné chování. Kopírování branche by mělo být 1:1, tj. timestamp by měl být stejný.

2022-02-21 09:38 UTC, tomasfejfar commented on tests/Common/BranchMetadataTest.php
> +        // delete some metadata from default
```suggestion
        // delete some metadata from branch
```

2022-02-21 12:04 UTC, martinjunger commented on tests/Common/BranchMetadataTest.php
> +        $this->assertNotSame($metadata[0]['timestamp'], $branchMetadata[0]['timestamp']);
viz https://github.com/keboola/connection/pull/3601#discussion_r810938176

2022-02-21 12:15 UTC, martinjunger commented on tests/Common/BranchMetadataTest.php
> +        // delete some metadata from default
upraveno, dik

2022-02-22 10:30 UTC, fejjo approved these changes
🙆‍♂️

2022-02-22 10:36 UTC, merged