Edit test for new behavior of delete trigger
keboola/storage-api-php-client pull request #786
Opened 2022-04-13 04:19 UTC by fejjo

Jira: KBC-XXX

Before asking for review make sure that:

- [ ] New client method(s) has tests
- [ ] Apiary file is updated
- [ ] You declared if there is a BC break or not (will affect next release of a client)

---

2022-04-14 11:21 UTC, tomasfejfar requested changes

2022-04-14 11:21 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        }
Tady by naopak mohla být expect exception snadno :)

2022-04-14 11:23 UTC, fejjo commented on tests/Common/TriggersTest.php
> +        $clientWithoutAdminToken->getTrigger((int) $trigger['id']);
> Zbytek teda reviewnu, až tohle bude fixlé a bude jasné, že ty testy testují všechny edge cases. 

Jo jasne sry

2022-04-14 16:17 UTC, fejjo commented on tests/Common/TriggersTest.php
> +        $this->assertSame(false, true);
ty jo dobry fail no :/

2022-04-14 18:14 UTC, fejjo commented
Testujem:
Trigger vytvoreny adminTokenom:
- nejde updatnut tokenom ktory nema opravnenia (canManageBuckets:false, opravnenie na orchestraciu)
- ide updatnut s tokenom s opravnenim 
- ide updatnut s master tokenom

Trigger vytvoreny nonAdmin tokenom
- ide updatnut nonAdmin tokenom s opravnenim ktory tento trigger vytvoril
- nejde updatnut s tokenom ktory nema opravnenia (canManageBuckets:false, opravnenie na orchestraciu)
- ide updatnut adminTokenom

Trigger vytvoreny nonAdmin tokenom:
- ide updatnut nonAdmin tokenom ktory ma opravnenia a nezalozil dani trigger
-

2022-04-14 18:34 UTC, fejjo commented
Testujem 

Trigger vytvoreny master tokenom
- nejde zmazat nonAdmin tokenom bez permission (canManageBuckets:false, opravnenie na orchestaciu)
- ide zmazat nonAdmin tokenom s opravnenimi
- ide zmazat admin tokenom

Trigger vytvoreny NonMastertokenom
- nejde zmazat nonAdmin tokenom bez opravneni
- ide zmazat non admin tokenom s opravnenym ktory ho nevytvoril
- ide zmazat admin tokenom
Trigger vytvorenu nonMaster tokenom
- ide zmazat tokenom ktory trigger nevytvoril a ma spravne privileges

2022-04-15 09:31 UTC, tomasfejfar approved these changes
Jen kosmetické věci

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        $clientWithoutAdminTokenWithoutPermission = $this->getClient(['url' => STORAGE_API_URL, 'token' => $newNonAdminTokenWithoutPermission['token']]);
Tohle je dost divný pattern v kombinaci s tím data providerem - vlastně to otestuješ 4x pro každý z těch dataproviderů :/ 

Ale už to nechme. 

Ideálně by to bylo:

`testTriggerCreatedByMasterTokenCanBeDeletedByToken` (tady by byly ty 4 tokeny co to s nima jde)
`testTriggerCreatedByMasterTokenCannotBeDeletedByToken` (tady by byl ten jeden co to s ním nejde)

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        }, $triggerList)));
AssertFalse má nevýhodu, že ti neřekne nic o tom, co bylo v tom poli. Je lepší assertovat že "není v poli"...

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        }, $triggerList)));
```
Failed asserting that true is false.
 /code/tests/Common/TriggersTest.php:637
 /code/tests/Common/TriggersTest.php:526
 /code/vendor/bshaffer/phpunit-retry-annotations/src/RetryTrait.php:33

```

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        }, $triggerList)));
```suggestion
        $this->assertNotContains($triggerId, array_map(function ($trigger) {
            return $trigger['id'];
        }, $triggerList));
```

Ale koukám, že to taky nevrací co v tom poli teda bylo :/

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +        }, $triggerList)));
Ale furt mi to přijde jako čitelnější error :)

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +    public function testDeleteTriggerCreatedByNonMasterToken(TokenCreateOptions $optionForToken)
Tohle nechápu, co testuje. To testuje, že když to může vytvořit, tak to může i smazat? To mi skoro přijde nadbytečné. 

Možná to aspoň přejmenovat
```suggestion
    public function testNonMasterTokenCanDeleteTriggerItCreated(TokenCreateOptions $optionForToken)
```

2022-04-15 09:31 UTC, tomasfejfar commented on tests/Common/TriggersTest.php
> +    public function testDeleteTriggerCreatedByNonMasterTokenDifferentToken(TokenCreateOptions $optionForToken)
```suggestion
    public function testDeleteTriggerCreatedByNonMasterTokenUsingDifferentToken(TokenCreateOptions $optionForToken)
```

2022-04-27 07:32 UTC, merged