KBC-1745 remove short config calls from api docs
keboola/storage-api-php-client pull request #810
Opened 2022-05-27 14:23 UTC by martinjunger

Jira: KBC-1745

Before asking for review make sure that:

- [x] New client method(s) has tests
- [x] Apiary file is updated
- [x] You declared if there is a BC break or not (will affect next release of a client)

---

2022-05-30 08:31 UTC, tomasfejfar requested changes
Plus bych řekl, že cíl byl, abysme nemuseli udržovat dokumentaci 2x, takže by u těch deprecated callů měly být odmazané ty dokumentace a zbýt tam jen deprecation notice a odkaz na to, že parametry jsou stejné jako u branched verze.

2022-05-30 08:31 UTC, tomasfejfar commented on apiary.apib
> +Use this API call to obtain the definition of component available in KBC.
To bych řekl, že není dobrý způsob. Mělo by to být zalinkované. Třeba při migraci na OpenAPI už nemusí být "above"

2022-05-30 08:31 UTC, tomasfejfar commented on apiary.apib
> +***Deprecated**, use method listed above.*
```suggestion
***Deprecated**, use the branch endpoint and set `branch/default`.*
```

Co takhle?

2022-05-31 09:47 UTC, martinjunger commented
- upravena deprecation message
- smazana dokumentace u deprecated endpointu

2022-05-31 14:43 UTC, tomasfejfar approved these changes
Přijde mi to OK (vzhledem k tomu, že je to jen dokumentace a ne kód), byť ta hláška takhle když to vidím není ideální. 

Možná by tomu pomohlo přejmenovat ty legacy endpointy z `List configurations (deprecated)` na `List configurations without branch in URL (deprecated)` nebo tak něco. Protože teď to vypadá takhle:
![image](https://user-images.githubusercontent.com/642928/171201159-f8f49413-c299-4939-bb70-caf3b5d6d2c5.png)
A z toho není bez dalších znalostí jasné, v čem je ten deprecated endpoint jiný (pokud nevíš, že v URL má být branch). 

Druhá možnost je fakt zalinkovat vždycky extra ten endpoint, který mají používat.

2022-06-06 08:21 UTC, tomasfejfar approved these changes
Takhle mi to přijde už OK.

2022-06-06 08:25 UTC, merged