change expected status code for job, since it's async
keboola/storage-api-php-client pull request #825
Opened 2022-06-22 06:08 UTC by zajca

Jira: KBC-2554

Before asking for review make sure that:

## Checklist

- [ ] New client method(s) has tests
- [ ] Apiary file is updated

## Release

  - [ ] major (BC break)
  - [x] minor (new feature)
  - [ ] patch (backwards compatible fix)
  - [ ] no release (just test changes)

2022-06-22 06:09 UTC, zajca commented
@tomasfejfar přemýšlám jestli udělat to async by default není přeca enom BC, protože při exception u jobu není status code jako při http exceptions.
https://github.com/keboola/storage-api-php-client/blob/482763ac3c4160155809515f22abf79ee4d5ab7b/src/Keboola/StorageApi/Client.php#L2400

2022-06-22 11:42 UTC, tomasfejfar reviewed
Dohodli jsme se, že s Zajca domluví s PS, jestli je to pro ně BC break nebo ne.

2022-06-22 11:43 UTC, zajca commented
Zatím nic moc, nevím jak dlůho tým chcu blokovat deployment https://keboola.slack.com/archives/CQB468K63/p1655883785512909

2022-06-23 06:39 UTC, tomasfejfar requested changes
LGTM, zkontroloval jsem, že v testech na njednom místě zbylo testování async vytváření. 

Jen teda SnowflakeDynamicBackendsTest::testWorkspaceCreateRequestObjectError checkuje http 400 a dělá to async... to si myslím, že by mělo být taky sync, ne?

2022-06-23 07:06 UTC, zajca commented
> LGTM, zkontroloval jsem, že v testech na njednom místě zbylo testování async vytváření.
> 
> Jen teda SnowflakeDynamicBackendsTest::testWorkspaceCreateRequestObjectError checkuje http 400 a dělá to async... to si myslím, že by mělo být taky sync, ne?

Nene to je cajk, tam kde sem to dal async to padá v controleru už při validaci, tam kde sa to validuje v jobu je to sync.

2022-06-23 07:23 UTC, tomasfejfar approved these changes

2022-06-23 07:24 UTC, merged