KBC-2713 test numeric column names
keboola/storage-api-php-client pull request #871
Opened 2022-08-25 22:08 UTC by jirkasemmler

Jira: KBC-[XXX](https://github.com/keboola/connection/pull/3949)

test 0,1 as column names for metadata

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2022-08-29 11:05 UTC, zajca requested changes
Test je v pohodě enom odstraň ty M1 srance, určitě chceme instalovat `msodbcsql17`, platform asi nevadí, ale nedokážu řéct jestli to može někde dělat problémy.

2022-08-29 11:28 UTC, jirkasemmler commented
> Test je v pohodě enom odstraň ty M1 srance, určitě chceme instalovat `msodbcsql17`, platform asi nevadí, ale nedokážu řéct jestli to može někde dělat problémy.

omg, sry, to urcite nemelo byt v PR

2022-08-29 12:04 UTC, zajca approved these changes

2022-10-17 12:51 UTC, zajca reviewed
Je to dobrý akorát mě napadlo, že sme mohli v `src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php` zrovna upravit ten vstup, když tam není columnName tak tak ho tam doplnit z indexu, bude to transparentní a nebudeme mět plno deprecations

2022-10-17 12:51 UTC, zajca approved these changes

2022-10-20 12:02 UTC, martinjunger commented
> Je to dobrý akorát mě napadlo, že sme mohli v `src/Keboola/StorageApi/Options/Metadata/TableMetadataUpdateOptions.php` zrovna upravit ten vstup, když tam není columnName tak tak ho tam doplnit z indexu, bude to transparentní a nebudeme mět plno deprecations

Pridal jsem backfill pro `columnName`.

2022-10-24 07:31 UTC, zajca approved these changes

2022-10-24 10:06 UTC, merged