KBC-2761 tokens use json
keboola/storage-api-php-client pull request #878
Opened 2022-09-02 14:43 UTC by martinjunger

Jira: KBC-2761

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [ ] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2022-09-02 14:47 UTC, martinjunger commented
Viz commit `send form-data/json content only is defined`: je to takhle v pohode, nic by to nemelo rozbit, ale na 100% si jistej nejsem. Kouknes na to prosim? Dik

2022-09-02 14:53 UTC, tomasfejfar commented
Proč byl problém, že se to pošle s prázdným jsonem? Nefungovalo to?

2022-09-05 09:53 UTC, martinjunger commented
>> Viz commit send form-data/json content only is defined: je to takhle v pohode, nic by to nemelo rozbit, ale na 100% si jistej nejsem. Kouknes na to prosim? Dik

> Proč byl problém, že se to pošle s prázdným jsonem? Nefungovalo to?

Ale jo, funguje, jen jsem potreboval druhy oci ;-)

2022-09-05 09:54 UTC, martinjunger commented
👉 uprava zakladnich metod presunuta do https://github.com/keboola/storage-api-php-client/pull/879

2022-09-06 14:45 UTC, martinjunger commented on src/Keboola/StorageApi/Client.php
> +        /** @phpstan-ignore-next-line */
je to legacy metoda, takze prijima `string`, ale posila dal jako `int` - upraveno pretypovanim

2022-09-07 13:25 UTC, tomasfejfar reviewed
Mrknul bys jestli ti taky padají některé testy lokálně nebo je to bug u mě? 
![image](https://user-images.githubusercontent.com/642928/188889691-c759a71a-a0ca-49aa-a749-65d1ed65e70c.png)

2022-09-07 13:25 UTC, tomasfejfar commented on src/Keboola/StorageApi/Tokens.php
> +    public function listTokens(): array
```suggestion
    /**
     * @return array
     */
    public function listTokens()
```

2022-09-07 13:25 UTC, tomasfejfar commented on src/Keboola/StorageApi/Tokens.php
> +    public function listTokens(): array
Byl by BC break v poděděné třídě.

2022-09-07 13:25 UTC, tomasfejfar commented on src/Keboola/StorageApi/Tokens.php
> +    public function getToken($id): array
pryč

2022-09-07 13:25 UTC, tomasfejfar commented on src/Keboola/StorageApi/Tokens.php
> +    public function createToken(TokenCreateOptions $options): array
pryč

2022-09-07 13:25 UTC, tomasfejfar commented on src/Keboola/StorageApi/Tokens.php
> +    public function getToken($id): array
do PHPDoc

2022-09-07 21:45 UTC, martinjunger commented
> Mrknul bys jestli ti taky padají některé testy lokálně nebo je to bug u mě?

Fixnul jsem formatovani `toParamsArray`, ktery se formatovalo specialne pro form-data:
```php
// original pro form-data
array (1)
   'bucketPermissions[out.c-API-tests]' => 'read'

// nove pro JSON
array (1)
   'bucketPermissions' => array (1)
   |  'out.c-API-tests' => 'read'
 ```

2022-09-08 12:25 UTC, martinjunger commented
ℹ️ Rebase

2022-09-12 12:11 UTC, tomasfejfar requested changes
https://keboola.slack.com/archives/CFVRE56UA/p1662984622586779

2022-09-12 12:31 UTC, martinjunger commented
> https://keboola.slack.com/archives/CFVRE56UA/p1662984622586779

Bude vyreseno po mergi https://github.com/keboola/storage-api-php-client/pull/894

2022-09-12 12:47 UTC, martinjunger commented
ℹ️ Rebase

2022-09-13 06:51 UTC, tomasfejfar approved these changes

2022-09-14 07:07 UTC, merged