KBC-2761 migrate Workspaces to JSON
keboola/storage-api-php-client pull request #883
Opened 2022-09-06 12:34 UTC by martinjunger

Jira: KBC-2761

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2022-09-07 12:35 UTC, jirkasemmler requested changes
opet nerozumim stejnym vecem
- bojim se dopadu tech assertu
- proc nevracime nic tady ani z POST requestu?

2022-09-08 12:43 UTC, martinjunger commented on src/Keboola/StorageApi/Workspaces.php
> +        $this->client->apiPostJson("workspaces/{$id}/load-clone", $options);
> proc nevracime nic tady ani z POST requestu?

Protoze se realne nic nevrati:
- vytvori se job
- vrati se `202 Accepted`
- `Client::request` [pocka](https://github.com/keboola/storage-api-php-client/blob/47a34f1d425d361675f92b76643904d626db165c/src/Keboola/StorageApi/Client.php#L2515-L2518) az job dobehne
    ```
        // wait for asynchronous task completion
        if ($handleAsyncTask && $response->getStatusCode() == 202) {
            return $this->handleAsyncTask($response);
        }
     ```
- potom vrati vysledek
- ❗ ale tenhle [job nic nevraci](https://github.com/keboola/connection/blob/b38947b19c53a4ff3ec0b474a51c698672ec5211/legacy-app/application/modules/storage/jobs/WorkspaceLoad.php#L77-L77), zaroven se s vysledkem nikde v testech nepocita

2022-09-08 12:44 UTC, martinjunger commented on src/Keboola/StorageApi/Workspaces.php
>      }
> proc nevracime nic tady ani z POST requestu?

Protoze se realne nic nevrati - viz komentar pobliz...

2022-09-08 12:50 UTC, martinjunger commented
ℹ️ Rebase

2022-09-13 06:23 UTC, jirkasemmler approved these changes
👍

2022-09-15 11:48 UTC, martinjunger commented
[Tag](https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=25873&view=logs&j=ae13dfb3-00c3-5552-9b00-63e26024fcba&t=48e25ff6-be86-558e-50b2-b8f91a4d5f0f&l=1770) spadnul jen na:
```
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	There were 4 errors:
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	1) Keboola\Test\Backend\Workspaces\LegacyWorkspacesSnowflakeTest::testLoadIncrementalNotNullable
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	Keboola\StorageApi\ClientException: Table in.c-API-tests-1eb2aae730941c1153220150a9cd2609f3bef5b7.languages load error: Likely datatype conversion: preg_match() expects parameter 2 to be string, int given
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2563
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2552
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2520
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2407
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Workspaces.php:88
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php:114
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/vendor/keboola/phpunit-retry-annotations/src/RetryTrait.php:32
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	2) Keboola\Test\Backend\Workspaces\LegacyWorkspacesSnowflakeTest::testLoadIncrementalNullable
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	Keboola\StorageApi\ClientException: Table in.c-API-tests-984cefc1fb61bb18c6cf682cb7e826e5532278af.languages load error: Likely datatype conversion: preg_match() expects parameter 2 to be string, int given
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2563
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2552
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2520
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2407
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Workspaces.php:88
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/tests/Backend/Workspaces/LegacyWorkspacesSnowflakeTest.php:204
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/vendor/keboola/phpunit-retry-annotations/src/RetryTrait.php:32
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	3) Keboola\Test\Backend\Workspaces\WorkspacesSnowflakeTest::testLoadIncrementalNullable
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	Keboola\StorageApi\ClientException: Table in.c-API-tests-f1d3b5de9c806f917eabf5440a549950612e040d.languages load error: Likely datatype conversion: preg_match() expects parameter 2 to be string, int given
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2563
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2552
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2520
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2407
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Workspaces.php:88
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/tests/Backend/Workspaces/WorkspacesSnowflakeTest.php:466
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/vendor/keboola/phpunit-retry-annotations/src/RetryTrait.php:32
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	4) Keboola\Test\Backend\Workspaces\WorkspacesSnowflakeTest::testLoadIncrementalNotNullable
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	Keboola\StorageApi\ClientException: Table in.c-API-tests-d90ea190ca91901bbee75c5a8a69c73dbb2c49e9.languages load error: Likely datatype conversion: preg_match() expects parameter 2 to be string, int given
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2563
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2552
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2520
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Client.php:2407
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/src/Keboola/StorageApi/Workspaces.php:88
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/tests/Backend/Workspaces/WorkspacesSnowflakeTest.php:562
15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	/code/vendor/keboola/phpunit-retry-annotations/src/RetryTrait.php:32
```

2022-09-15 14:41 UTC, martinjunger commented
> [Tag](https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=25873&view=logs&j=ae13dfb3-00c3-5552-9b00-63e26024fcba&t=48e25ff6-be86-558e-50b2-b8f91a4d5f0f&l=1770) spadnul jen na:
> 
> ```
> 15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	1) Keboola\Test\Backend\Workspaces\LegacyWorkspacesSnowflakeTest::testLoadIncrementalNotNullable
> 15:13:14-UTC - paratest-backend-snowflake-abs-part-1  -	Keboola\StorageApi\ClientException: Table in.c-API-tests-1eb2aae730941c1153220150a9cd2609f3bef5b7.languages load error: Likely datatype conversion: preg_match() expects parameter 2 to be string, int given
> ...
> ```

Fixnuto v https://github.com/keboola/connection/pull/3991

2022-12-12 13:42 UTC, martinjunger commented
🏷️ Tag 3: https://dev.azure.com/keboola-dev/Connection%20build/_build/results?buildId=28569&view=results

2023-02-28 15:42 UTC, merged