Test create/drop WS for bigquery
keboola/storage-api-php-client pull request #933
Opened 2022-11-22 09:00 UTC by romanbracinik

Jira: BIG-45
MainPr: https://github.com/keboola/connection/pull/4083

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2022-11-23 09:35 UTC, zajca requested changes
Testy vypadajů cajk, idu to zkusit

2022-11-23 09:46 UTC, zajca commented
@romanbracinik tady je ještě potřeba přidat BQ https://github.com/keboola/storage-api-php-client/blob/2c63423460ccbb1aa90725ebc94fd8b9a3fd05cd/tests/Backend/WorkspaceConnectionTrait.php#L20
jinak to nepojede.
![image](https://user-images.githubusercontent.com/180148/203515792-24539510-be5c-4204-ab84-4390631ae9ea.png)

2022-11-23 09:52 UTC, romanbracinik commented
> @romanbracinik tady je ještě potřeba přidat BQ
> 
> https://github.com/keboola/storage-api-php-client/blob/2c63423460ccbb1aa90725ebc94fd8b9a3fd05cd/tests/Backend/WorkspaceConnectionTrait.php#L20
> 
> 
> jinak to nepojede.
> ![image](https://user-images.githubusercontent.com/180148/203515792-24539510-be5c-4204-ab84-4390631ae9ea.png)

Jo jasne :) ja som to pridaval az v dalsom PR presunul som to sem este som to neskusal ci to funguje

2022-11-24 07:12 UTC, zajca approved these changes

2022-11-24 08:03 UTC, merged