Add snflk/bq mixed suite
keboola/storage-api-php-client pull request #949
Opened 2022-12-06 18:21 UTC by romanbracinik

Jira: [BIG-38](https://keboola.atlassian.net/browse/BIG-38), [BIG-39](https://keboola.atlassian.net/browse/BIG-39)
MainPr: https://github.com/keboola/connection/pull/4098

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2022-12-08 14:11 UTC, jirkasemmler requested changes
malickosti

2022-12-08 14:11 UTC, jirkasemmler commented on tests/Backend/MixedSnowflakeBigquery/SharingTest.php
> +                $this->_client->$shareMethod($bucketId, $async ?? []);
huh, to je zas chutovka. dej tam prosim malej komentar :)

2022-12-08 14:11 UTC, jirkasemmler commented on tests/Backend/MixedSnowflakeBigquery/SharingTest.php
> +        // create table in WS and insert some data
tydle komentare jsou super, u tohoto testu docela nutnosti, muzes prosim stejne popsat dalsi kroky dole? Dobre se mi podle toho napisou TD testy, bo je budu muset upravit

2022-12-08 16:29 UTC, romanbracinik commented on tests/Backend/MixedSnowflakeBigquery/SharingTest.php
> +        // create table in WS and insert some data
V podstate v TD ti bude staci pridat ten dataProvider a ten switch vsekto ostatne kontrolujes v tych testoch TD ale pridal som tam komentare

2022-12-09 12:26 UTC, jirkasemmler approved these changes
👍

2022-12-15 08:37 UTC, romanbracinik commented
rebase

2022-12-15 12:42 UTC, merged