KBC-2941 update table uses JSON
keboola/storage-api-php-client pull request #954
Opened 2022-12-13 09:07 UTC by martinjunger

Jira: KBC-2941
Connection: https://github.com/keboola/connection/pull/4112

Before asking for review make sure that:

## Checklist

- [x] New client method(s) has tests
- [x] Apiary file is updated

## Release

  - [x] I gave the PR a proper label:
    * major (BC break)
    * minor (new feature)
    * patch (backwards compatible fix)
    * no release (just test changes)

2023-02-15 16:21 UTC, jirkasemmler reviewed
nemela by byt jeste uprava v apiary? A imho by to chtelo videt tag s a bez upravy testu, protoze by mela fungovat i puvodni verze

2023-02-16 10:56 UTC, martinjunger commented
> nemela by byt jeste uprava v apiary?

Co bys tam chtel upravovat? Parametry se nemenili.

> A imho by to chtelo videt tag s a bez upravy testu, protoze by mela fungovat i puvodni verze

Jestli narazis na posledni incident, tak ten se tykal jen DELETE metody. POST a PUT se nemenili (ani v zari) z `query` na `form-data`, takze ani zmena z `form-data` na `json` to nerozhodi. OK, tag pustim.

2023-02-21 09:34 UTC, jirkasemmler commented
apiary - zmenil bych ten example. ale priznavam, ze jinde jsme to nedelali. Chtelo by to pak asi projit obecne
![image](https://user-images.githubusercontent.com/13363655/220305777-5b0c40b8-410b-4899-b897-335338d62782.png)

a na incident nenarazim. Jen jsem chtel vedet, jestli to mame checknute, ze nove connection bude frcet jak se starym tak i novym requstem. To jsem checknul lokalne, takze toto je cajk. 

Upravis tedy prosim jen ten example na apiary? thx

2023-02-21 09:34 UTC, jirkasemmler requested changes
viz posledni komentar

2023-02-21 09:43 UTC, tomasfejfar commented
IMHO jsme tam přidávali requesty s JSONem a s form-data, ne?

2023-02-21 10:15 UTC, martinjunger commented
> apiary - zmenil bych ten example. ale priznavam, ze jinde jsme to nedelali. Chtelo by to pak asi projit obecne ...
> 
> Upravis tedy prosim jen ten example na apiary? thx

Tohle jsme zatim neupravovali nikde, plan byl udelat to potom najednou u vsech endpointu. Tak bych to nedelal ani tady. Mel by na to byt nekde tiket, zkusim ho najit...

2023-02-21 10:36 UTC, tomasfejfar commented
Jo, asi máš pravdu, jediná změna byla u delete rows, jinak ne. https://keboola.docs.apiary.io/#reference/tables/manage-table-rows/delete-table-rows

2023-02-21 16:28 UTC, martinjunger commented
> > apiary - zmenil bych ten example. ale priznavam, ze jinde jsme to nedelali. Chtelo by to pak asi projit obecne ...
> > Upravis tedy prosim jen ten example na apiary? thx
> 
> Tohle jsme zatim neupravovali nikde, plan byl udelat to potom najednou u vsech endpointu. Tak bych to nedelal ani tady. Mel by na to byt nekde tiket, zkusim ho najit...

Tiket jsem nenasel, nejspis to bylo puvodne soucasti https://keboola.atlassian.net/browse/CT-553.
Vytvoril jsem novy, at je to jasny: https://keboola.atlassian.net/browse/CT-882.

2023-02-22 07:41 UTC, jirkasemmler approved these changes
souhlas s tim apiary

2023-02-22 09:53 UTC, merged